# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rmessage.proto\"8\n\x18VerticalJoystickPosition\x12\r\n\x05index\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\x02\x42#\n!ca.frozen.rpicameraviewer.message')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VERTICALJOYSTICKPOSITION = _descriptor.Descriptor(
  name='VerticalJoystickPosition',
  full_name='VerticalJoystickPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='VerticalJoystickPosition.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='VerticalJoystickPosition.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['VerticalJoystickPosition'] = _VERTICALJOYSTICKPOSITION

VerticalJoystickPosition = _reflection.GeneratedProtocolMessageType('VerticalJoystickPosition', (_message.Message,), dict(
  DESCRIPTOR = _VERTICALJOYSTICKPOSITION,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:VerticalJoystickPosition)
  ))
_sym_db.RegisterMessage(VerticalJoystickPosition)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!ca.frozen.rpicameraviewer.message'))
# @@protoc_insertion_point(module_scope)
